package server.db.repos;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import jakarta.persistence.EntityExistsException;
import org.hibernate.NonUniqueObjectException;
import org.hibernate.exception.ConstraintViolationException;
import server.db.RepositoryTestBase;
import server.db.entities.Difficulty;
import server.db.entities.Exam;
import server.db.entities.ExamVersion;
import server.db.entities.ExamVersionStatus;
import server.db.entities.Question;
import server.db.entities.QuestionVersion;
import server.db.projections.AuthoredExamHeader;
import server.db.projections.AuthoredVersionRow;
import server.db.projections.ExamCompositionHeader;
import server.db.projections.PinCandidate;
import server.db.projections.PinnedQuestion;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * The exam builder's write surface, on whichever engine the leaf binds (E7).
 *
 * <p>Everything here is engine-agnostic, <b>including the two unique constraints</b>. H2's schema
 * is generated by Hibernate from the entities, and {@code ExamVersionQuestion} declares both
 * uniques on its {@code @Table} - so they exist on both engines and the duplicate-question and
 * duplicate-ordinal tests belong here, where the fast suite runs them too. {@code H2Support} says
 * this in as many words; an earlier version of this javadoc claimed the opposite and exiled both
 * tests to MySQL, which meant T-3.9's named acceptance rule was guarded only when
 * {@code HSTS_REQUIRE_MYSQL=true}.
 *
 * <p>What H2 genuinely cannot see is the composite foreign key and the {@code CHECK} constraints,
 * because the entities map no associations and declare no {@code @Check}. Those tests, and the
 * collation-dependent ones, live in the MySQL leaf where they can actually fail.
 *
 * <p>The fixture builds its own questions and exams rather than extending the base seed, which is
 * deliberate: what a test depends on is then visible in the test.
 */
abstract class ExamBuildRepositoryContract extends RepositoryTestBase {

    private static final Instant WHEN =
            Instant.parse("2026-08-24T09:00:00Z").truncatedTo(ChronoUnit.MILLIS);

    private final ExamBuildRepository repository = new ExamBuildRepository();

    // ===================== Creating ======================================

    @Test
    @DisplayName("a new exam gets a display id built from its subject, course and serial (S-10)")
    void insertExamAllocatesDisplayId() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));

        Exam stored = inTx(session -> session.get(Exam.class, examId));
        assertThat(stored.getDisplayId()).isEqualTo(SUBJECT_MATH + COURSE_ALGEBRA + "01");
        assertThat(stored.getCourseCode()).isEqualTo(COURSE_ALGEBRA);
        assertThat(stored.getAuthorId()).isEqualTo(danaId);
    }

    @Test
    @DisplayName("serials advance per course, so the second exam is 02 and not 01 again")
    void serialsAdvancePerCourse() {
        inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long second = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long other = inTx(session -> repository.insertExam(session, COURSE_CALCULUS, danaId));

        assertThat(displayIdOf(second)).isEqualTo(SUBJECT_MATH + COURSE_ALGEBRA + "02");
        // A different course restarts at 01: the serial is per course, not global.
        assertThat(displayIdOf(other)).isEqualTo(SUBJECT_MATH + COURSE_CALCULUS + "01");
    }

    @Test
    @DisplayName("a version is written as a DRAFT and never straight into the queue")
    void versionsStartAsDrafts() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));

        long versionId = inTx(session -> repository.insertDraftVersion(session, examId, 1,
                "מבחן אלגברה", 90, "בהצלחה", "מחוון", WHEN));

        ExamVersion stored = inTx(session -> session.get(ExamVersion.class, versionId));
        assertThat(stored.getStatus()).isEqualTo(ExamVersionStatus.DRAFT);
        assertThat(stored.getVersionNo()).isEqualTo(1);
        assertThat(stored.getName()).isEqualTo("מבחן אלגברה");
        assertThat(stored.getDurationMinutes()).isEqualTo(90);
        assertThat(stored.getStudentText()).isEqualTo("בהצלחה");
        assertThat(stored.getTeacherText()).isEqualTo("מחוון");
        assertThat(stored.getRejectedReason()).isNull();
    }

    @Test
    @DisplayName("the latest version number is 0 before there is one, then the highest")
    void latestVersionNo() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));

        int beforeAnyVersion = inTx(session -> repository.findLatestVersionNo(session, examId));
        assertThat(beforeAnyVersion).isZero();

        inTx(session -> repository.insertDraftVersion(session, examId, 1, "v1", 60, null, null, WHEN));
        inTx(session -> repository.insertDraftVersion(session, examId, 2, "v2", 60, null, null, WHEN));

        int afterTwo = inTx(session -> repository.findLatestVersionNo(session, examId));
        assertThat(afterTwo).isEqualTo(2);
    }

    // ===================== The composition ================================

    @Test
    @DisplayName("the composition comes back in paper order, not insertion order")
    void compositionIsOrdered() {
        long versionId = draftVersion();
        long first = questionWithVersions("שאלה א", 1);
        long second = questionWithVersions("שאלה ב", 1);
        long third = questionWithVersions("שאלה ג", 1);

        // Deliberately written in an order that is not the paper order, so an ORDER BY that was
        // dropped would show up here rather than passing by accident.
        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, third), third, 30, 3),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 40, 1),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, second), second, 30, 2)));
            return null;
        });

        List<PinnedQuestion> paper = inTx(session -> repository.findComposition(session, versionId));

        assertThat(paper).extracting(PinnedQuestion::ord).containsExactly(1, 2, 3);
        assertThat(paper).extracting(PinnedQuestion::text)
                .containsExactly("שאלה א", "שאלה ב", "שאלה ג");
        assertThat(paper).extracting(PinnedQuestion::points).containsExactly(40, 30, 30);
    }

    @Test
    @DisplayName("re-saving the same questions at new positions replaces rather than collides")
    void replacingAtNewOrdinalsDoesNotCollide() {
        // Re-pinning the same questions at new ordinals is the case that would collide if the
        // delete were queued rather than executed. It is not: a bulk createMutationQuery delete
        // goes straight to the database, so the rows are gone before the first insert is
        // enqueued and no flush is needed between them. This test is the evidence for that
        // claim - it stayed green when both flushes were removed - so it is also what would go
        // red if someone made the delete lazy. Creating a composition never exercises it; only
        // editing one does.
        long versionId = draftVersion();
        long first = questionWithVersions("שאלה א", 1);
        long second = questionWithVersions("שאלה ב", 1);

        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 50, 1),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, second), second, 50, 2)));
            return null;
        });

        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, second), second, 60, 1),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 40, 2)));
            return null;
        });

        List<PinnedQuestion> paper = inTx(session -> repository.findComposition(session, versionId));

        assertThat(paper).extracting(PinnedQuestion::text).containsExactly("שאלה ב", "שאלה א");
        assertThat(paper).extracting(PinnedQuestion::points).containsExactly(60, 40);
    }

    @Test
    @DisplayName("calling it twice in one transaction is refused, which is why §5.6 says once")
    void twoCompositionWritesInOneTransactionAreRefused() {
        // The measurement behind replaceComposition's javadoc. A bulk delete goes straight to the
        // database, which is why no flush is needed between the delete and the inserts - and is
        // equally why it does NOT evict anything from the persistence context. ExamVersionQuestion
        // has an assigned composite id, so the instances the first call persisted are still
        // managed under those keys and the second call's re-pin collides inside Hibernate before
        // any SQL is attempted.
        //
        // Pinned as a test rather than asserted in prose because the javadoc's neighbouring claim
        // says "measured rather than assumed", and two claims formatted alike had better both be
        // measured. Contract §5.6 makes each write one transaction, so no supported path does
        // this; a compose-then-adjust path would need session.clear() or a second transaction.
        long versionId = draftVersion();
        long first = questionWithVersions("שאלה א", 1);
        long second = questionWithVersions("שאלה ב", 1);

        assertThatThrownBy(() -> runInTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 100, 1)));
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 50, 1),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, second), second, 50, 2)));
        }))
                .isInstanceOf(EntityExistsException.class)
                .hasRootCauseInstanceOf(NonUniqueObjectException.class);
    }

    @Test
    @DisplayName("a shorter save leaves none of the questions it dropped behind")
    void replacingWithFewerQuestionsDropsTheRest() {
        long versionId = draftVersion();
        long first = questionWithVersions("שאלה א", 1);
        long second = questionWithVersions("שאלה ב", 1);

        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 50, 1),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, second), second, 50, 2)));
            return null;
        });
        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 100, 1)));
            return null;
        });

        List<PinnedQuestion> paper = inTx(session -> repository.findComposition(session, versionId));

        assertThat(paper).extracting(PinnedQuestion::text).containsExactly("שאלה א");
    }

    @Test
    @DisplayName("a question whose bank version moved on reports both numbers (E7.7)")
    void pinnedVersionIsComparedAgainstTheLatest() {
        long versionId = draftVersion();
        long moved = questionWithVersions("שאלה שהתעדכנה", 3);
        long stable = questionWithVersions("שאלה יציבה", 1);

        // Pin version 1 of the question that now has three, which is exactly the state the
        // builder badges.
        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(versionIdOf(session, moved, 1), moved, 50, 1),
                    new ExamBuildRepository.Pin(versionIdOf(session, stable, 1), stable, 50, 2)));
            return null;
        });

        List<PinnedQuestion> paper = inTx(session -> repository.findComposition(session, versionId));

        assertThat(paper.get(0).pinnedVersionNo()).isEqualTo(1);
        assertThat(paper.get(0).latestVersionNo()).isEqualTo(3);
        assertThat(paper.get(1).pinnedVersionNo()).isEqualTo(1);
        assertThat(paper.get(1).latestVersionNo()).isEqualTo(1);
    }

    @Test
    @DisplayName("the paper reports whether a question has an illustration, without its bytes")
    void hasImageIsReportedWithoutFetchingIt() {
        long versionId = draftVersion();
        long withImage = questionWithImage();
        long withoutImage = questionWithVersions("בלי תמונה", 1);

        inTx(session -> {
            repository.replaceComposition(session, versionId, List.of(
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, withImage), withImage, 50, 1),
                    new ExamBuildRepository.Pin(latestVersionIdOf(session, withoutImage), withoutImage, 50, 2)));
            return null;
        });

        List<PinnedQuestion> paper = inTx(session -> repository.findComposition(session, versionId));

        assertThat(paper).extracting(PinnedQuestion::hasImage).containsExactly(true, false);
    }

    @Test
    @DisplayName("the same question through two of its versions is refused by the schema (T-3.9)")
    void oneQuestionCannotAppearTwiceThroughTwoVersions() {
        // PRD §6's "duplicate question in exam -> prevented", and the constraint behind it. The
        // service refuses this first with a sentence naming the question, because the constraint's
        // own message is not something a teacher can act on. This asserts the backstop is really
        // there, so a service check that gets removed does not silently let a duplicate onto a
        // paper. It lives in the contract because H2 reproduces the unique too.
        long versionId = draftVersion();
        long questionId = questionWithVersions("שאלה כפולה", 2);

        assertThatThrownBy(() -> runInTx(session -> repository.replaceComposition(session, versionId,
                List.of(new ExamBuildRepository.Pin(versionIdOf(session, questionId, 1), questionId, 50, 1),
                        new ExamBuildRepository.Pin(versionIdOf(session, questionId, 2), questionId, 50, 2)))))
                // Named, not merely non-null. isNotNull() passes for any throwable, including an
                // NPE from a fixture helper returning a null version id - and the assertion below
                // would agree with it, because nothing was written either way. Both engines report
                // the constraint name, though they decorate it differently (H2 appends _INDEX_n,
                // MySQL prefixes the table), so this contains rather than equals.
                .isInstanceOf(ConstraintViolationException.class)
                .hasMessageContaining("uq_exam_version_questions_question");

        List<PinnedQuestion> afterRollback = inTx(session -> repository.findComposition(session, versionId));
        assertThat(afterRollback)
                .as("the whole transaction rolled back, so no half-written paper survives")
                .isEmpty();
    }

    @Test
    @DisplayName("two questions cannot share a position on the paper")
    void ordinalsAreUniqueWithinAVersion() {
        long versionId = draftVersion();
        long first = questionWithVersions("שאלה א", 1);
        long second = questionWithVersions("שאלה ב", 1);

        assertThatThrownBy(() -> runInTx(session -> repository.replaceComposition(session, versionId,
                List.of(new ExamBuildRepository.Pin(latestVersionIdOf(session, first), first, 50, 1),
                        new ExamBuildRepository.Pin(latestVersionIdOf(session, second), second, 50, 1)))))
                .as("uq_exam_version_questions_ord: two questions at position 1 is not a paper")
                .isInstanceOf(ConstraintViolationException.class)
                .hasMessageContaining("uq_exam_version_questions_ord");
    }

    // ===================== The header =====================================

    @Test
    @DisplayName("the header carries the course, the author and the optimistic token")
    void headerCarriesWhatEveryAnswerNeeds() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long versionId = inTx(session -> repository.insertDraftVersion(session, examId, 1,
                "מבחן אלגברה", 90, "בהצלחה", "מחוון", WHEN));

        ExamCompositionHeader header = inTx(session ->
                repository.findCompositionHeader(session, versionId)).orElseThrow();

        assertThat(header.examId()).isEqualTo(examId);
        assertThat(header.displayId6()).isEqualTo(SUBJECT_MATH + COURSE_ALGEBRA + "01");
        assertThat(header.courseCode()).isEqualTo(COURSE_ALGEBRA);
        assertThat(header.courseName()).isEqualTo("אלגברה");
        assertThat(header.authorId()).isEqualTo(danaId);
        assertThat(header.authorName()).isEqualTo("דנה כהן");
        assertThat(header.versionNo()).isEqualTo(1);
        assertThat(header.status()).isEqualTo(ExamVersionStatus.DRAFT);
        assertThat(header.durationMinutes()).isEqualTo(90);
        assertThat(header.rejectedReason()).isNull();
        assertThat(header.createdAt()).isEqualTo(WHEN);
        assertThat(header.lockVersion()).isZero();
    }

    @Test
    @DisplayName("the header's token is the version's own, not the exam's and not a default")
    void headerCarriesTheVersionsOwnLockVersion() {
        // The header test above reads a version at lock 0, which is also what the exam row and a
        // hardcoded literal would give - so it could not tell the three apart. Writing the version
        // twice moves its token to 2 while the exam's stays at 0.
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long versionId = inTx(session -> repository.insertDraftVersion(session, examId, 1,
                "מבחן", 90, null, null, WHEN));
        approve(versionId);
        reject(versionId, "לא מספיק");

        ExamCompositionHeader header = inTx(session ->
                repository.findCompositionHeader(session, versionId)).orElseThrow();

        assertThat(header.lockVersion()).isEqualTo(2);
        assertThat(header.durationMinutes()).isEqualTo(90);
    }

    @Test
    @DisplayName("an unknown version is an empty header, not an exception")
    void unknownVersionIsEmpty() {
        Optional<ExamCompositionHeader> header =
                inTx(session -> repository.findCompositionHeader(session, 987654L));

        assertThat(header).isEmpty();
    }

    @Test
    @DisplayName("a draft loaded for writing can be edited in place, and only its four fields move")
    void draftsAreEditedThroughTheManagedEntity() {
        // findVersionToWrite plus editDraft are the pair EXAM_VERSION_SAVE uses, and both had
        // zero coverage until this test: they were written for a service that does not exist yet,
        // which is exactly how an untested method reaches a PR looking finished.
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long versionId = inTx(session -> repository.insertDraftVersion(session, examId, 1,
                "השם הישן", 60, "לתלמיד", "למורה", WHEN));

        runInTx(session -> repository.findVersionToWrite(session, versionId).orElseThrow()
                .editDraft("השם החדש", 120, null, "מחוון חדש"));

        ExamVersion stored = inTx(session -> session.get(ExamVersion.class, versionId));
        assertThat(stored.getName()).isEqualTo("השם החדש");
        assertThat(stored.getDurationMinutes()).isEqualTo(120);
        assertThat(stored.getStudentText()).isNull();
        assertThat(stored.getTeacherText()).isEqualTo("מחוון חדש");

        // A save never changes what a version IS. Editing a non-draft is REVISE, which makes a
        // new row instead.
        assertThat(stored.getStatus()).isEqualTo(ExamVersionStatus.DRAFT);
        assertThat(stored.getVersionNo()).isEqualTo(1);
        assertThat(stored.getRejectedReason()).isNull();
        assertThat(stored.getCreatedAt()).isEqualTo(WHEN);
        assertThat(stored.getLockVersion())
                .as("the write bumped the optimistic token, which is what the next save checks")
                .isEqualTo(1);
    }

    @Test
    @DisplayName("an unknown version is empty rather than an exception, so the service answers NOT_FOUND")
    void unknownVersionToWriteIsEmpty() {
        Optional<ExamVersion> missing = inTx(session -> repository.findVersionToWrite(session, 987654L));

        assertThat(missing).isEmpty();
    }

    // ===================== Resolving what she wants to pin ================

    @Test
    @DisplayName("a pin resolves to its owning question, its course and its deleted flag")
    void pinCandidatesResolveWhatTheClientDidNotSend() {
        long live = questionWithVersions("חיה", 2);
        long deleted = questionWithVersions("מחוקה", 1);
        softDelete(deleted);

        List<PinCandidate> candidates = inTx(session -> repository.findPinCandidates(session,
                List.of(versionIdOf(session, live, 1), versionIdOf(session, live, 2),
                        versionIdOf(session, deleted, 1))));

        assertThat(candidates).hasSize(3);
        // Two different versions of one question resolve to the SAME questionId, which is what
        // makes T-3.9's duplicate detectable at all.
        assertThat(candidates).filteredOn(c -> c.questionId() == live).hasSize(2);
        assertThat(candidates).allMatch(c -> c.courseCode().equals(COURSE_ALGEBRA));
        assertThat(candidates).filteredOn(PinCandidate::deleted)
                .extracting(PinCandidate::questionId).containsExactly(deleted);
    }

    @Test
    @DisplayName("an unknown question version is simply absent, so the validator can name its slot")
    void unknownPinsAreAbsentRatherThanNull() {
        long live = questionWithVersions("חיה", 1);

        long liveVersionId = inTx(session -> versionIdOf(session, live, 1));
        List<PinCandidate> candidates = inTx(session ->
                repository.findPinCandidates(session, List.of(liveVersionId, 987654L)));

        assertThat(candidates).extracting(PinCandidate::questionVersionId)
                .containsExactly(liveVersionId);
    }

    @Test
    @DisplayName("asking about no questions runs no query and yields nothing")
    void emptyPinListIsEmpty() {
        List<PinCandidate> fromEmpty = inTx(session -> repository.findPinCandidates(session, List.of()));
        List<PinCandidate> fromNull = inTx(session -> repository.findPinCandidates(session, null));

        assertThat(fromEmpty).isEmpty();
        assertThat(fromNull).isEmpty();
    }

    // ===================== The author's list ==============================

    @Test
    @DisplayName("the exam list is scoped to its author and never shows a colleague's exam")
    void examListIsAuthorScoped() {
        long hers = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        inTx(session -> repository.insertDraftVersion(session, hers, 1, "שלה", 60, null, null, WHEN));
        long his = inTx(session -> repository.insertExam(session, COURSE_CALCULUS, rinaId));
        inTx(session -> repository.insertDraftVersion(session, his, 1, "שלו", 60, null, null, WHEN));

        List<AuthoredExamHeader> mine = inTx(session -> repository.findAuthoredExams(session, danaId));

        assertThat(mine).extracting(AuthoredExamHeader::examId).containsExactly(hers);
        assertThat(mine).extracting(AuthoredExamHeader::name).containsExactly("שלה");
        assertThat(mine).extracting(AuthoredExamHeader::courseName).containsExactly("אלגברה");
    }

    @Test
    @DisplayName("the exam list is ordered by display id, which needs two exams to mean anything")
    void examListIsOrderedByDisplayId() {
        // Every other list test seeds one exam per author, so the ORDER BY could be deleted with
        // nothing failing and the list would then render in whatever order the engine returned -
        // which differs between H2 and InnoDB.
        long calculus = inTx(session -> repository.insertExam(session, COURSE_CALCULUS, danaId));
        inTx(session -> repository.insertDraftVersion(session, calculus, 1, "חשבון", 60, null, null, WHEN));
        long algebra = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        inTx(session -> repository.insertDraftVersion(session, algebra, 1, "אלגברה", 60, null, null, WHEN));

        List<AuthoredExamHeader> mine = inTx(session -> repository.findAuthoredExams(session, danaId));

        // Algebra is course 11 and Calculus is 12, so display id orders Algebra first even though
        // it was created second.
        assertThat(mine).extracting(AuthoredExamHeader::examId).containsExactly(algebra, calculus);
        assertThat(mine).extracting(AuthoredExamHeader::displayId6)
                .containsExactly(SUBJECT_MATH + COURSE_ALGEBRA + "01",
                        SUBJECT_MATH + COURSE_CALCULUS + "01");
    }

    @Test
    @DisplayName("the list names an exam by its highest version, drafts included")
    void listNamesExamByItsHighestVersion() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        inTx(session -> repository.insertDraftVersion(session, examId, 1, "השם הישן", 60, null, null, WHEN));
        inTx(session -> repository.insertDraftVersion(session, examId, 2, "השם החדש", 60, null, null, WHEN));

        List<AuthoredExamHeader> exams = inTx(session -> repository.findAuthoredExams(session, danaId));

        assertThat(exams).singleElement().satisfies(exam -> {
            assertThat(exam.name()).isEqualTo("השם החדש");
            assertThat(exam.latestVersionNo()).isEqualTo(2);
        });
    }

    @Test
    @DisplayName("every version is listed, drafts included, newest first")
    void versionListIncludesDraftsNewestFirst() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long v1 = inTx(session -> repository.insertDraftVersion(session, examId, 1, "v1", 60, null, null, WHEN));
        long v2 = inTx(session -> repository.insertDraftVersion(session, examId, 2, "v2", 60, null, null, WHEN));
        approve(v1);

        List<AuthoredVersionRow> rows = inTx(session -> repository.findAuthoredVersions(session, danaId));

        assertThat(rows).extracting(AuthoredVersionRow::versionNo).containsExactly(2, 1);
        assertThat(rows).extracting(AuthoredVersionRow::status)
                .containsExactly(ExamVersionStatus.DRAFT, ExamVersionStatus.APPROVED);
        assertThat(rows).extracting(AuthoredVersionRow::examId).containsOnly(examId);
        assertThat(rows).extracting(AuthoredVersionRow::examVersionId).containsExactly(v2, v1);

        // The optimistic token, and it has to be THIS version's. approve() bumped v1's @Version
        // to 1 while v2 was never written again, so the two rows carry different tokens and a
        // constructor expression that picked up the wrong column - the duration, the exam's own
        // lock, or a literal - can no longer pass. Every other assertion in this class read a row
        // whose lockVersion was 0, which is the default, so a swap survived the whole suite.
        assertThat(rows).extracting(AuthoredVersionRow::lockVersion).containsExactly(0, 1);
        assertThat(rows).extracting(AuthoredVersionRow::durationMinutes).containsOnly(60);
        assertThat(rows).extracting(AuthoredVersionRow::createdAt).containsOnly(WHEN);
    }

    @Test
    @DisplayName("the version list is author-scoped too, not only the exam list")
    void versionListIsAuthorScoped() {
        // Added after a planted mutation: defeating the author scope in findAuthoredVersions
        // failed nothing, because every other list test seeds one author. Two reads carry this
        // scope and only one of them was guarded, which is the shape where a widening reaches
        // production through the read nobody wrote a test against.
        long hers = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        inTx(session -> repository.insertDraftVersion(session, hers, 1, "שלה", 60, null, null, WHEN));
        long his = inTx(session -> repository.insertExam(session, COURSE_CALCULUS, rinaId));
        long hisVersion = inTx(session ->
                repository.insertDraftVersion(session, his, 1, "שלו", 60, null, null, WHEN));

        List<AuthoredVersionRow> mine = inTx(session -> repository.findAuthoredVersions(session, danaId));

        assertThat(mine).extracting(AuthoredVersionRow::examId).containsOnly(hers);
        assertThat(mine).extracting(AuthoredVersionRow::examVersionId).doesNotContain(hisVersion);
    }

    @Test
    @DisplayName("a rejected version carries its reason onto the list (F4.2)")
    void rejectedReasonReachesTheList() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        long versionId = inTx(session -> repository.insertDraftVersion(session, examId, 1,
                "v1", 60, null, null, WHEN));
        reject(versionId, "חסרות שאלות ברמה קשה");

        List<AuthoredVersionRow> rows = inTx(session -> repository.findAuthoredVersions(session, danaId));

        assertThat(rows).singleElement().satisfies(row -> {
            assertThat(row.status()).isEqualTo(ExamVersionStatus.REJECTED);
            assertThat(row.rejectedReason()).isEqualTo("חסרות שאלות ברמה קשה");
            // reject() wrote the row, so its @Version moved off the default.
            assertThat(row.lockVersion()).isEqualTo(1);
        });
    }

    // ===================== Fixture ========================================

    /** An exam with one draft version, which most composition tests want and none vary. */
    private long draftVersion() {
        long examId = inTx(session -> repository.insertExam(session, COURSE_ALGEBRA, danaId));
        return inTx(session -> repository.insertDraftVersion(session, examId, 1,
                "מבחן", 90, null, null, WHEN));
    }

    /** A question in Algebra with {@code versions} versions, numbered from 1. */
    private long questionWithVersions(String text, int versions) {
        long questionId = persistQuestion();
        for (int versionNo = 1; versionNo <= versions; versionNo++) {
            int number = versionNo;
            runInTx(session -> session.persist(new QuestionVersion(questionId, number, text,
                    "1", "2", "3", "4", (byte) 1, "פונקציות", Difficulty.EASY,
                    null, danaId, WHEN)));
        }
        return questionId;
    }

    private long questionWithImage() {
        long questionId = persistQuestion();
        runInTx(session -> session.persist(new QuestionVersion(questionId, 1, "עם תמונה",
                "1", "2", "3", "4", (byte) 1, "פונקציות", Difficulty.EASY,
                new byte[] {1, 2, 3}, danaId, WHEN)));
        return questionId;
    }

    private long persistQuestion() {
        return inTx(session -> {
            short serial = (short) (countQuestions(session) + 1);
            Question question = new Question(COURSE_ALGEBRA, serial,
                    COURSE_ALGEBRA + String.format("%03d", serial));
            session.persist(question);
            session.flush();
            return question.getId();
        });
    }

    private long countQuestions(org.hibernate.Session session) {
        return session.createQuery("select count(q) from Question q", Long.class).uniqueResult();
    }

    private void softDelete(long questionId) {
        runInTx(session -> session.get(Question.class, questionId).setDeletedAt(WHEN));
    }

    private void approve(long examVersionId) {
        runInTx(session -> session.get(ExamVersion.class, examVersionId).approve());
    }

    private void reject(long examVersionId, String reason) {
        runInTx(session -> session.get(ExamVersion.class, examVersionId).reject(reason));
    }

    private String displayIdOf(long examId) {
        return inTx(session -> session.get(Exam.class, examId).getDisplayId());
    }

    private long versionIdOf(org.hibernate.Session session, long questionId, int versionNo) {
        return session.createQuery("""
                        select qv.id from QuestionVersion qv
                        where qv.questionId = :questionId and qv.versionNo = :versionNo
                        """, Long.class)
                .setParameter("questionId", questionId)
                .setParameter("versionNo", versionNo)
                .uniqueResult();
    }

    private long latestVersionIdOf(org.hibernate.Session session, long questionId) {
        return session.createQuery("""
                        select qv.id from QuestionVersion qv
                        where qv.questionId = :questionId
                          and qv.versionNo = (select max(later.versionNo) from QuestionVersion later
                                              where later.questionId = :questionId)
                        """, Long.class)
                .setParameter("questionId", questionId)
                .uniqueResult();
    }
}
