package server.db;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.hibernate.SessionFactory;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Builds a throwaway in-memory database for the fast test suite (E2.13).
 *
 * <h2>What this proves, and what it does not</h2>
 *
 * <p>The schema here is generated by Hibernate <em>from the entities themselves</em>.
 * That makes it quick and self-contained — no server, no cleanup, a fresh database per
 * test — and it is genuinely useful for exercising repository logic and mapping
 * round-trips.
 *
 * <p>It proves nothing about the real schema. Comparing entities against a schema built
 * from those same entities is circular. That check belongs to
 * {@link EntityMappingValidationTest} and {@link SchemaColumnComparisonTest}, which
 * migrate with Flyway first.
 *
 * <p><b>What H2 cannot see</b>, and therefore what a test written only against it may be
 * wrong about:
 * <ul>
 *   <li><b>Foreign keys and CHECK constraints.</b> The entities map no associations and
 *       declare no {@code @Check}, so schema-gen emits neither. Nothing here enforces
 *       "correct answer is 1..4", "points 1..100", "close_at &gt; open_at", or the
 *       composite key that keeps {@code exam_version_questions.question_id} honest.</li>
 *   <li><b>Collation.</b> Production is {@code utf8mb4_unicode_ci}, which compares
 *       case-insensitively — load-bearing twice: entering a 4-character execution code
 *       (C-1) and comparing answers for the pairwise-distinct rule (ADR-016). H2's MySQL
 *       mode does not reproduce it, so a case-sensitivity test can pass here and fail on
 *       MySQL, or the reverse.</li>
 *   <li><b>JSON semantics.</b> The three JSON columns are {@code mediumtext} here and
 *       native {@code JSON} in production, so MySQL's key reordering and whitespace
 *       normalisation are invisible.</li>
 * </ul>
 *
 * <p>Unique constraints <em>are</em> reproduced — the entities declare them explicitly
 * for exactly this reason, so the E2.14 allocator tests in PR 2b can actually collide.
 *
 * <p>Keep the division clear when adding tests: <b>behaviour</b> here, <b>schema
 * agreement</b> in the MySQL suite.
 */
final class H2Support {

    private H2Support() {
        // static helper — no instances
    }

    /**
     * A fresh database, factory and pool. MySQL compatibility mode is on so the SQL
     * Hibernate emits is close to production, and the name is unique per call so two
     * tests running in the same JVM cannot see each other's rows.
     *
     * @return an open database; close it when the test finishes
     */
    static H2Db fresh() {
        return fresh(Map.of());
    }

    /**
     * A fresh database with extra Hibernate settings.
     *
     * <p>Exists so a test can install a {@code StatementInspector} and assert on the SQL
     * Hibernate actually emits — the only way to prove that a projection query never
     * <em>fetches</em> a column, as opposed to fetching it and leaving it out of the result
     * type. E2.12 needs exactly that distinction.
     *
     * @param extraSettings settings merged over the defaults
     * @return an open database; close it when the test finishes
     */
    static H2Db fresh(Map<String, Object> extraSettings) {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:hsts_" + UUID.randomUUID().toString().replace("-", "")
                + ";MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        config.setUsername("sa");
        config.setPassword("");
        config.setMaximumPoolSize(4);
        config.setPoolName("hsts-h2-test");

        Map<String, Object> settings = new HashMap<>();
        settings.put("hibernate.hbm2ddl.auto", "create");
        settings.putAll(extraSettings);

        HikariDataSource pool = new HikariDataSource(config);
        try {
            return new H2Db(HibernateUtil.build(pool, settings), pool);
        } catch (RuntimeException | Error e) {
            pool.close();
            throw e;
        }
    }

    /**
     * A factory and the pool underneath it, closed together.
     *
     * <p>The pool has to be handed back rather than hidden, because
     * {@link HibernateUtil#build} does not own the {@code DataSource} it is given and
     * therefore never closes it. Returning only the {@code SessionFactory} left one
     * pool — and, with {@code DB_CLOSE_DELAY=-1}, one whole database — alive per call for
     * the life of the JVM. Harmless at four test classes; not at one per repository in
     * PR 2b.
     *
     * @param factory the session factory
     * @param pool    the connection pool it draws from
     */
    record H2Db(SessionFactory factory, HikariDataSource pool) implements AutoCloseable {

        @Override
        public void close() {
            factory.close();
            pool.close();
        }
    }
}
